FROM python:3.10

ARG AWS_S3_BUCKET_NAME
ARG LOG_MODE
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
ENV LOG_MODE=${LOG_MODE}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

WORKDIR /script
COPY . /script
RUN pip install boto3 botocore
CMD ["python", "./main.py"]
