name: Build container from script

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/sg-check:latest" .
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Docker push
        run: |
          docker push "${{ secrets.DOCKERHUB_USERNAME }}"/sg-check:latest
