name: Run container daily

on:
  schedule:
    - cron: '0 13 * * *'
jobs:
  run-docker:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - name: Print Envs (Debug)
      run: |
        echo "Printing AWS_ACCESS_KEY_ID Length"
        echo "${#AWS_ACCESS_KEY_ID}"
        echo "Printing AWS_SECRET_ACCESS_KEY Length"
        echo "${#AWS_SECRET_ACCESS_KEY}"
    - name: testing cache
      run: |
        echo "123"
    - name: Docker login
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Run Docker Container
      run: |
        docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY "${{ secrets.DOCKERHUB_USERNAME }}"/sg-check:latest
