name: Run container daily

on:
#  schedule:
#    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  run-docker:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      LOG_MODE: ${{ secrets.LOG_MODE }}
    steps:
    - name: Docker login
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Run Docker Container
      run: |
        docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        -e AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME \
        -e LOG_MODE=$LOG_MODE "${{ secrets.DOCKERHUB_USERNAME }}"/sg-check:latest
